/* ==========================================================================
   بيانات المنهج السعودي والمواد الدراسية وقاعدة أسئلة الاختبارات
   ========================================================================== */

const THAKAA_DATA = {
  stages: [
    {
      id: "primary",
      title: "المرحلة الابتدائية",
      icon: "fa-child-rebounding",
      description:
        "تأسيس رصين وفق المنهج السعودي من الصف الأول حتى السادس الابتدائي",
      grades: [
        { id: "p1", name: "الصف الأول الابتدائي" },
        { id: "p2", name: "الصف الثاني الابتدائي" },
        { id: "p3", name: "الصف الثالث الابتدائي" },
        { id: "p4", name: "الصف الرابع الابتدائي" },
        { id: "p5", name: "الصف الخامس الابتدائي" },
        { id: "p6", name: "الصف السادس الابتدائي" },
      ],
    },
    {
      id: "intermediate",
      title: "المرحلة المتوسطة",
      icon: "fa-graduation-cap",
      description:
        "تطوير المفاهيم والمهارات العلمية والتحليلية من الصف الأول حتى الثالث المتوسط",
      grades: [
        { id: "m1", name: "الصف الأول المتوسط" },
        { id: "m2", name: "الصف الثاني المتوسط" },
        { id: "m3", name: "الصف الثالث المتوسط" },
      ],
    },
    {
      id: "secondary",
      title: "المرحلة الثانوية",
      icon: "fa-award",
      description:
        "إعداد متميز للمسارات الأكاديمية والجامعية واختبارات القدرات والتحصيلي",
      grades: [
        { id: "s1", name: "الصف الأول الثانوي" },
        { id: "s2", name: "الصف الثاني الثانوي (مسارات)" },
        { id: "s3", name: "الصف الثالث الثانوي (مسارات)" },
      ],
    },
  ],

  subjects: [
    // ==================== 1. المرحلة الابتدائية ====================
    {
      id: "sub-p-math",
      stageId: "primary",
      title: "الرياضيات",
      term: "الفصل الدراسي الأول",
      themeColor: "#0d47a1",
      icon: "fa-calculator",
      description:
        "الأعداد والعمليات الحسابية الأساسية، الهندسة والأشكال القياسية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "ما هو ناتج جمع 5 + 7؟",
          options: ["11", "12", "13", "14"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ما هو القاسم المشترك الأكبر للعددين 12 و 18؟",
          options: ["3", "6", "9", "12"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "إذا كان ثمن 5 دفاتر هو 25 ريالاً، فما ثمن 8 دفاتر؟",
          options: ["35 ريالاً", "40 ريالاً", "45 ريالاً", "50 ريالاً"],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متوسط",
          question: "ما هو محيط مربع طول ضلعه 6 سم؟",
          options: ["18 سم", "24 سم", "36 سم", "12 سم"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "الكسر العشري المكافئ للكسر الاعتيادي (1/4) هو:",
          options: ["0.5", "0.25", "0.75", "0.4"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-p-arabic",
      stageId: "primary",
      title: "لغتي",
      term: "الفصل الدراسي الأول",
      themeColor: "#8d6e63",
      icon: "fa-book-open",
      description:
        "الحروف والقواعد النحوية، الإملاء، الفهم القرائي والأساليب اللغوية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "ما نوع كلمة 'المدرسة' في اللغة العربية؟",
          options: ["اسم", "فعل", "حرف", "ظرف"],
          correctIndex: 0,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ما هي علامة رفع الفاعل إذا كان جمع مذكر سالم؟",
          options: ["الضمة", "الألف", "الواو", "النون"],
          correctIndex: 2,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "ما إعراب كلمة 'مجتهداً' في جملة: 'أصبح الطالبُ مجتهداً'؟",
          options: [
            "فاعل مرفوع",
            "خبر أصبح منصوب",
            "اسم أصبح مرفوع",
            "مفعول به منصوب",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "الكلمة التي تبدأ بهمزة وصل من الكلمات التالية هي:",
          options: ["أحمد", "إكرام", "استمع", "أقبل"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "ما نوع الأسلوب في جملة: 'لا تهمل واجباتك المدرسية'؟",
          options: ["أسلوب نفي", "أسلوب نهي", "أسلوب أمر", "أسلوب استفهام"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-p-science",
      stageId: "primary",
      title: "العلوم",
      term: "الفصل الدراسي الأول",
      themeColor: "#2e7d32",
      icon: "fa-flask",
      description:
        "الخلايا والأجهزة الحيوية، الأنظمة البيئية، والتغيرات الكيميائية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "ما هي وحدة البناء الأساسية في جسم الكائن الحي؟",
          options: ["العضو", "النسيج", "الخلية", "الجهاز"],
          correctIndex: 2,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "تسمى العملية التي يصنع بها النبات غذاءه بـ:",
          options: ["التنفس", "البناء الضوئي", "الندح", "الامتصاص"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "أي مما يلي يُعد مثالاً على التغير الكيميائي؟",
          options: [
            "انصهار الجليد",
            "صدأ الحديد",
            "تقطيع الورق",
            "ذوبان السكر في الماء",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "أقرب كوكب إلى الشمس في مجموعتنا الشمسية هو:",
          options: ["الزهرة", "عطارد", "المريخ", "الأرض"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "الجهاز المسؤول عن ضخ وتوزيع الدم في جسم الإنسان هو:",
          options: [
            "الجهاز الهضمي",
            "الجهاز التنفسي",
            "جهاز الدوران (القلب والأوعية)",
            "الجهاز العصبي",
          ],
          correctIndex: 2,
        },
      ],
    },
    {
      id: "sub-p-islamic",
      stageId: "primary",
      title: "الدراسات الإسلامية",
      term: "الفصل الدراسي الأول",
      themeColor: "#1b5e20",
      icon: "fa-kaaba",
      description: "التوحيد، الفقه والسلوك، والحديث والسيرة النبوية الشريفة.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "أول ركن من أركان الإسلام الخمسة هو:",
          options: ["إقام الصلاة", "شهادة أن لا إله إلا الله وأن محمداً رسول الله", "إيتاء الزكاة", "صوم رمضان"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ما هو حكم صلاة الجماعة للرجال القادرين في المسجد؟",
          options: ["واجبة", "سنة مؤكدة", "مستحبة", "مباحة"],
          correctIndex: 0,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "ما المعنى الصحيح للتوسل المشروع؟",
          options: [
            "دعاء الأموات والقبور",
            "التقرب إلى الله تعالى بأسمائه وصفاته والأعمال الصالحة",
            "طلب النفع من الأشجار والأحجار",
            "الاعتماد على غير الله",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "كم عدد أركان الإيمان في الإسلام؟",
          options: ["أربعة أركان", "خمسة أركان", "ستة أركان", "سبعة أركان"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "السورة التي تعدل في فضلها ثلث القرآن الكريم هي:",
          options: ["سورة الفاتحة", "سورة الإخلاص", "سورة الفلق", "سورة الكوثر"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-p-english",
      stageId: "primary",
      title: "اللغة الإنجليزية (We Can)",
      term: "الفصل الدراسي الأول",
      themeColor: "#e91e63",
      icon: "fa-language",
      description:
        "Basic vocabulary, phonics, grammar structure, and conversational English.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "Choose the correct subject pronoun: '___ is a teacher.'",
          options: ["He", "They", "We", "You"],
          correctIndex: 0,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "Complete the sentence: 'Yesterday, I ___ to school.'",
          options: ["go", "went", "gone", "going"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "Which sentence is grammatically correct in Simple Present?",
          options: [
            "She play football every day.",
            "She plays football every day.",
            "She playing football every day.",
            "She played football tomorrow.",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "What is the correct plural form of the noun 'Child'?",
          options: ["Childs", "Childrens", "Children", "Childes"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "What is the opposite of the adjective 'Cold'?",
          options: ["Warm", "Fast", "Hot", "Dark"],
          correctIndex: 2,
        },
      ],
    },

    // ==================== 2. المرحلة المتوسطة ====================
    {
      id: "sub-m-english",
      stageId: "intermediate",
      title: "اللغة الإنجليزية (Super Goal)",
      term: "الجزء الأول من المقرر",
      themeColor: "#e91e63",
      icon: "fa-language",
      description:
        "قواعد اللغة (Grammar)، المفردات وتراكيب الجمل، مهارات الاستيعاب والمحادثة.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "Choose the correct pronoun: 'Ali is a doctor. _____ works in a hospital.'",
          options: ["She", "He", "They", "We"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "سهل",
          question: "What is the past tense of the irregular verb 'go'?",
          options: ["goed", "went", "going", "gone"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "Choose the correct sentence in the Present Continuous tense:",
          options: [
            "They are playing football now.",
            "They play football now.",
            "They played football now.",
            "They will playing football now.",
          ],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متوسط",
          question: "Which comparative adjective correctly completes: 'This car is _____ than that one.'?",
          options: ["fast", "faster", "fastest", "more faster"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "Choose the correct relative pronoun: 'The teacher _____ teaches us English is very kind.'",
          options: ["which", "who", "where", "whose"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-m-math",
      stageId: "intermediate",
      title: "الرياضيات",
      term: "الجزء الأول من المقرر",
      themeColor: "#0288d1",
      icon: "fa-square-root-variable",
      description:
        "الجبر، المعادلات والمتباينات الخطية، والدوال والمصفوفات والقياس.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "حل المعادلة س + 5 = 12 هو س = :",
          options: ["5", "7", "17", "6"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ميل المستقيم المار بالنقطتين (1 ، 2) و (3 ، 6) يساوي:",
          options: ["1", "2", "3", "4"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "ما هما حلا المعادلة التربيعية: س² - 9 = 0 ؟",
          options: ["3 و -3", "9 و -9", "3 و 0", "9 و 0"],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "مجموع قياسات الزوايا الداخلية لأي مثلث يساوي:",
          options: ["90°", "180°", "360°", "270°"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "ما ناتج تبسيط المقدار: 2³ × 2² ؟",
          options: ["2⁶ (64)", "2⁵ (32)", "4⁵", "2¹"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-m-arabic",
      stageId: "intermediate",
      title: "لغتي الخالدة",
      term: "الجزء الأول من المقرر",
      themeColor: "#d81b60",
      icon: "fa-pen-nib",
      description: "التحليل الأدبي، الصنف اللغوي، التمييز، البدل والاستثناء.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "ما نوع الأسلوب اللغوي في: 'ما أجملَ السماءَ!'؟",
          options: ["أسلوب تفضيل", "أسلوب تعجب", "أسلوب استثناء", "أسلوب شرط"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "في جملة 'قرأتُ الكتابَ نصفَهُ'، كلمة 'نصفه' تُعرب:",
          options: ["بدل بعض من كل", "بدل اشتمال", "بدل مطابق", "مفعول به ثانٍ"],
          correctIndex: 0,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "ما وزن الفعل 'استغفرَ' في الميزان الصرفي؟",
          options: ["استفعل", "افتعل", "تفاعل", "فعلل"],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "من الأدوات التي تجزم فعلاً مضارعاً واحداً:",
          options: ["لن", "لم", "إن", "لعل"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "اسم المفعول المشتق من الفعل الثلاثي 'كَتَبَ' هو:",
          options: ["كاتب", "مكتوب", "كتابة", "مكتب"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-m-science",
      stageId: "intermediate",
      title: "العلوم",
      term: "الجزء الأول من المقرر",
      themeColor: "#1565c0",
      icon: "fa-atom",
      description:
        "طبيعة العلم، جدول العناصر الكيميائية، الحركة والقوانين الفيزيائية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "قانون نيوتن الأول في الحركة يسمى أيضاً بقانون:",
          options: ["القصور الذاتي", "التسارع", "الفعل ورد الفعل", "الجاذبية الكونية"],
          correctIndex: 0,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ما هي الجسيمات سالبة الشحنة التي تدور حول نواة الذرة؟",
          options: ["البروتونات", "النيوترونات", "الإلكترونات", "الكواركات"],
          correctIndex: 2,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "احسب متوسط السرعة لسيارة قطعت مسافة 150 كم خلال 3 ساعات:",
          options: ["45 كم/س", "50 كم/س", "60 كم/س", "75 كم/س"],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "الوحدة الدولية المستخدمة لقياس شدة التيار الكهربائي هي:",
          options: ["الفولت", "الأوم", "الأمبير", "الواط"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "الرقم الهيدروجيني (pH) للمحلول المتعادل تماماً كالماء النقي هو:",
          options: ["0", "7", "14", "1"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-m-social",
      stageId: "intermediate",
      title: "الدراسات الاجتماعية",
      term: "الجزء الأول من المقرر",
      themeColor: "#6a1b9a",
      icon: "fa-map-marked-alt",
      description:
        "جغرافية المملكة العربية السعودية، الأنظمة والإنتاج الوطني ورؤية 2030.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "الخطة التنموية الشاملة للمملكة العربية السعودية هي:",
          options: ["رؤية 2020", "رؤية 2025", "رؤية 2030", "رؤية 2040"],
          correctIndex: 2,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "تقع المملكة العربية السعودية في الركن الجنوبي الغربي من قارة:",
          options: ["أفريقيا", "آسيا", "أوروبا", "أستراليا"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "النظام الذي يحدد شكل الدولة ونظام الحكم في المملكة هو:",
          options: [
            "النظام الأساسي للحكم",
            "نظام المناطق",
            "نظام مجلس الوزراء",
            "نظام الشورى",
          ],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "تم توحيد المملكة العربية السعودية وإعلان تسميتها رسمياً في عام:",
          options: ["1319 هـ", "1343 هـ", "1351 هـ", "1373 هـ"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "يحد المملكة العربية السعودية من جهة الغرب مسطح مائي هو:",
          options: ["الخليج العربي", "البحر الأحمر", "بحر العرب", "المحيط الهندي"],
          correctIndex: 1,
        },
      ],
    },

    {
      id: "sub-m-tech",
      stageId: "intermediate",
      title: "التقنية الرقمية",
      term: "الجزء الأول من المقرر",
      themeColor: "#1565c0",
      icon: "fa-laptop-code",
      description:
        "الأساسيات البرمجية، المواطنة الرقمية، وإدارة معالجة البيانات والأمن السيبراني.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "الوحدة المسؤولة عن معالجة الأوامر والعمليات الحسابية في الحاسب هي:",
          options: [
            "ذاكرة الوصول العشوائي RAM",
            "وحدة المعالجة المركزية CPU",
            "القرص الصلب HDD",
            "شاشة العرض",
          ],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "مصطلح 'Phishing' في مجال الأمن السيبراني يقصد به:",
          options: [
            "تحديث برامج التشغيل",
            "التصيد الاحتيالي لسرقة بيانات المستخدمين",
            "زيادة سرعة معالجة البيانات",
            "ضغط الملفات الرقمية",
          ],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "في لغات البرمجة، وظيفة حلقة التكرار 'For Loop' هي:",
          options: [
            "حذف المتغيرات من الذاكرة",
            "تكرار تنفيذ مقطع برمجي لعدد محدد من المرات",
            "إنشاء قاعدة بيانات جديدة",
            "إيقاف تشغيل الجهاز",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "الامتداد القياسي لملفات صفحات الويب هو:",
          options: [".exe", ".html", ".mp3", ".docx"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "الشبكة التي تربط أجهزة الحاسب عبر نطاق جغرافي واسع كالدول تسمى:",
          options: ["LAN", "PAN", "WAN", "MAN"],
          correctIndex: 2,
        },
      ],
    },

    // ==================== 3. المرحلة الثانوية ====================
    {
      id: "sub-s-physics",
      stageId: "secondary",
      title: "الفيزياء",
      term: "مسارات المشتركة والتخصصية",
      themeColor: "#4a148c",
      icon: "fa-bolt",
      description:
        "المدخل إلى الفيزياء، الرياضيات والفيزياء، الحركة والتسارع وقوانين نيوتن.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "وحدة قياس القوة في النظام الدولي للوحدات (SI) هي:",
          options: ["الجول (J)", "النيوتن (N)", "الواط (W)", "الباسكال (Pa)"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "تسارع الجسم يتناسب طردياً مع القوة المحصلة وعكسياً مع:",
          options: ["المسافة المقطوعة", "كتلة الجسم (m)", "الزمن المستغرق", "السرعة المتجهة"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "إذا سقط جسم سقوطاً حراً من السكون، فما سرعته بعد 4 ثوانٍ؟ (بفرض g = 9.8 م/ث²)",
          options: ["19.6 م/ث", "39.2 م/ث", "49.0 م/ث", "9.8 م/ث"],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "'الشغل المبذول على جسم يساوي التغير في طاقته الحركية'؛ هذا نص:",
          options: [
            "قانون حفظ الشحنة",
            "نظرية الشغل - الطاقة",
            "قانون كبلر الأول",
            "مبدأ باسكال",
          ],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "أي من الموجات التالية تُعد موجة كهرومغناطيسية تنتقل في الفراغ؟",
          options: ["موجات الصوت", "موجات الماء", "موجات الضوء", "موجات الزلازل"],
          correctIndex: 2,
        },
      ],
    },
    {
      id: "sub-s-chemistry",
      stageId: "secondary",
      title: "الكيمياء",
      term: "مسار الصحة والحياة / العام",
      themeColor: "#00695c",
      icon: "fa-vial",
      description:
        "التركيب الذري، الجدول الدوري، الروابط الكيميائية والحسابات الكيميائية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "الرمز الكيميائي لعنصر الصوديوم في الجدول الدوري هو:",
          options: ["So", "Na", "K", "N"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "عدد أفوجادرو يمثل عدد الجسيمات أو الذرات الموجودة في:",
          options: ["جرام واحد", "مول واحد (1 mol)", "لتر واحد", "ذرة واحدة"],
          correctIndex: 1,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "نوع الرابطة الكيميائية في مركب كلوريد الصوديوم (NaCl) هي:",
          options: [
            "رابطة تساهمية غير قطبية",
            "رابطة أيونية",
            "رابطة فلزية",
            "رابطة هيدروجينية",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "قوى التجاذب الضعيفة الناتجة عن حركة الإلكترونات في الجزيئات غير القطبية تسمى:",
          options: [
            "الرابطة الهيدروجينية",
            "قوى ثنائية القطب",
            "قوى التشتت (قوى لندن)",
            "الرابطة التناسقية",
          ],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "المادة التي تزيد من سرعة التفاعل الكيميائي دون أن تُستهلك فيه هي:",
          options: ["المادة الناتجة", "العامل المحفز (الحافز)", "المادة المتفاعلة", "المثبط"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-s-biology",
      stageId: "secondary",
      title: "الأحياء",
      term: "مسار الصحة والحياة",
      themeColor: "#2e7d32",
      icon: "fa-dna",
      description:
        "أجهزة جسم الإنسان، الجهاز العصبي، المناعة، وعلم الوراثة المتقدم.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "الحمض النووي الذي يحمل الشفرة والتعليمات الوراثية في الخلايا هو:",
          options: ["ATP", "DNA", "RNA", "الليبيدات"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "خلايا الدم المسؤولة عن الدفاع عن الجسم ومقاومة الأمراض هي:",
          options: [
            "خلايا الدم الحمراء",
            "الصفائح الدموية",
            "خلايا الدم البيضاء",
            "بلازما الدم",
          ],
          correctIndex: 2,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "الهرمون الذي يفرزه البنكرياس لخفض مستوى السكر في الدم هو:",
          options: ["الجلوكاجون", "الأدرينالين", "الأنسولين", "الثيروكسين"],
          correctIndex: 2,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "الانقسام الخلوي الذي ينتج عنه 4 خلايا جنسية أحادية المجموعة الكروموسومية (1n) هو:",
          options: [
            "الانقسام المتساوي",
            "الانقسام المنصف (الميوزي)",
            "الانشطار الثنائي",
            "التجدد",
          ],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "عضية الخلية المسؤولة عن التنفس الخلوي وإنتاج جزيئات الطاقة (ATP) هي:",
          options: [
            "جهاز جولجي",
            "الميتوكندريا",
            "الريبوسومات",
            "الشبكة الإندوبلازمية",
          ],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-s-ai",
      stageId: "secondary",
      title: "الذكاء الاصطناعي والتقنية الرقمية",
      term: "مسار الحاسب والهندسة",
      themeColor: "#1565c0",
      icon: "fa-microchip",
      description:
        "خوارزميات التعلم الآلي، الشبكات العصبية الإصطناعية ورؤية الحاسب.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "مفهوم التعلم الآلي (Machine Learning) يتمثل في:",
          options: [
            "كتابة أكواد برمجية ثابتة فقط",
            "قدرة الخوارزمية على التعلم من البيانات والتنبؤ بالنتائج",
            "تنظيف ذاكرة التخزين الصلبة",
            "تصميم واجهات المستخدم البسيطة",
          ],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "الشبكات العصبية التلافيفية (CNN) متخصصة بشكل رئيسي في مجال:",
          options: [
            "معالجة الصوت فقط",
            "ضغط الملفات النصية",
            "معالجة الصور ورؤية الحاسب (Computer Vision)",
            "إدارة قواعد البيانات العادية",
          ],
          correctIndex: 2,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "الفرق الجوهري للتعلم الخاضع للإشراف (Supervised) هو وجود:",
          options: [
            "بيانات معنونة ومصنفة مسبقاً (Labeled Data)",
            "معالجات فائقة السرعة فقط",
            "لغات برمجة معقدة دون بيانات",
            "اتصال دائم بالإنترنت",
          ],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "لغة البرمجة الأكثر انتشاراً واستخداماً في بناء نماذج الذكاء الاصطناعي هي:",
          options: ["HTML", "PHP", "Python", "Pascal"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "فرع الذكاء الاصطناعي الذي يمكن الحاسب من فهم وتحليل النصوص واللغة البشرية هو:",
          options: [
            "معالجة اللغات الطبيعية (NLP)",
            "إنترنت الأشياء (IoT)",
            "الحوسبة السحابية",
            "الواقع المعزز (AR)",
          ],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "sub-s-math",
      stageId: "secondary",
      title: "الرياضيات (1 - 2 - 3)",
      term: "مسارات المشتركة والتخصصية",
      themeColor: "#0288d1",
      icon: "fa-square-root-variable",
      description:
        "التفاضل والتكامل، الدوال المثلثية، والمجموعات والمتجهات الفضائية.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "مشتقة الدالة د(س) = س² هي:",
          options: ["س", "2س", "2", "س³"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "ما هي القيمة الدقيقة لـ جا(90°) [sin 90°]؟",
          options: ["0", "0.5", "1", "-1"],
          correctIndex: 2,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "تكامل الدالة (2س) بالنسبة لـ س [∫ 2x dx] يساوي:",
          options: ["س² + جـ", "2س² + جـ", "س + جـ", "2 + جـ"],
          correctIndex: 0,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "أساس دالة اللوغاريتم الطبيعي (ln) هو الثابت الرياضي:",
          options: ["10", "2", "العدد النيبيري (e ≈ 2.718)", "0"],
          correctIndex: 2,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "في المتتابعة الحسابية: 3 ، 7 ، 11 ، 15 ، ... ما هو أساس المتتابعة (د)؟",
          options: ["3", "4", "5", "7"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "sub-s-english",
      stageId: "secondary",
      title: "اللغة الإنجليزية (Mega Goal)",
      term: "مسارات المشتركة والتخصصية",
      themeColor: "#e91e63",
      icon: "fa-language",
      description:
        "Advanced reading comprehension, essays, writing mechanics, and conversational fluency.",
      questions: [
        {
          id: 1,
          difficulty: "سهل",
          question: "Select the correct conditional form: 'If I ___ you, I would study harder.'",
          options: ["am", "were", "was", "be"],
          correctIndex: 1,
        },
        {
          id: 2,
          difficulty: "متوسط",
          question: "What is the closest synonym of the word 'Enthusiastic'?",
          options: ["Eager", "Lazy", "Bored", "Quiet"],
          correctIndex: 0,
        },
        {
          id: 3,
          difficulty: "متوسط",
          question: "Which tense is used in: 'By next year, they will have finished the project'?",
          options: [
            "Future Continuous",
            "Future Perfect",
            "Present Perfect",
            "Past Perfect",
          ],
          correctIndex: 1,
        },
        {
          id: 4,
          difficulty: "متقدم",
          question: "Convert to passive: 'The manager approved the plan.' -> 'The plan ___ by the manager.'",
          options: ["is approved", "was approved", "has approved", "were approved"],
          correctIndex: 1,
        },
        {
          id: 5,
          difficulty: "متقدم",
          question: "Which conjunction expresses concession/contrast in: '___ it was late, he continued working.'?",
          options: ["Because", "Although", "Therefore", "Since"],
          correctIndex: 1,
        },
      ],
    },
  ],

  parentServices: [
    {
      id: "tracking",
      title: "طلب متابعة مستوى طالب",
      icon: "fa-chart-line",
      desc: "احصل على تقرير أسبوعي شامل يتضمن الأداء في الاختبارات ونسبة الإنجاز.",
    },
    {
      id: "consultation",
      title: "استشارة تعليمية وتربوية",
      icon: "fa-user-tie",
      desc: "جلسة استشارية مع نخبة من الخبراء التربويين لتوجيه الطالب أكاديمياً ونفسياً.",
    },
    {
      id: "enrollment",
      title: "تسجيل ابن / ابنة بالمنصة",
      icon: "fa-user-plus",
      desc: "إلحاق جديد بخطة تعليمية فردية تناسب احتياجات وطموح الطالب.",
    },
  ],
};
